services:
  app:
    image: gglamer/django-console:latest
    depends_on:
      - otel-collector
    environment:
      APP_API_TOKEN: ${APP_API_TOKEN:?APP_API_TOKEN is required}
      APP_SIGNING_KEY: ${APP_SIGNING_KEY:?APP_SIGNING_KEY is required}
      APP_CORE_API_SERVICE_TOKEN: ${APP_CORE_API_SERVICE_TOKEN:?APP_CORE_API_SERVICE_TOKEN is required}
      APP_NAME: web-python-skelet
      APP_ENV: docker
      APP_HTTP_HOST: 0.0.0.0
      APP_HTTP_PORT: '8123'
      APP_DB_ENGINE: sqlite
      APP_DB_NAME: db.sqlite3
      APP_LOGGING_LEVEL: INFO
      APP_LOGGING_OUTPUT: otel
      APP_LOGGING_FORMAT: json
      APP_METRICS_ENABLED: 'true'
      APP_TRACING_ENABLED: 'true'
      APP_OTEL_SERVICE_NAME: web-python-skelet
      APP_OTEL_LOGS_ENDPOINT: http://otel-collector:4318/v1/logs
      APP_OTEL_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      APP_OTEL_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_METRIC_EXPORT_INTERVAL: '1000'
      APP_API_TOKEN_HEADER: X-API-Token
      DJANGO_SUPERUSER_USERNAME: gglamer
      DJANGO_SUPERUSER_EMAIL: aza@ya.ru
      DJANGO_SUPERUSER_PASSWORD: 123
      DJANGO_SETTINGS_MODULE: adapter.http.django.settings
    ports:
      - '127.0.0.1:8123:8123'

  otel-collector:
    image: grafana/otel-lgtm:latest
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - lgtm-data:/data

volumes:
  lgtm-data:
