# Generated by Django 6.0.3 on 2026-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
