# Generated by Django 6.0.3 on 2026-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntryRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_email', models.CharField(db_index=True, max_length=254)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('target_type', models.CharField(db_index=True, max_length=255)),
                ('target_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('payload_json', models.JSONField()),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
